version: '3.8'

services:
  load_balancer:
    build:
      context: ./load_balancer_req
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3
    environment:
      - LOAD_BALANCER_ALGORITHM=round-robin


  server1:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=1
    ports:
      - "5001:5000"

  server2:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=2
    ports:
      - "5002:5000"

  server3:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - SERVER_ID=3
    ports:
      - "5003:5000"

